# Generated by Django 3.2.8 on 2022-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('job_type', models.CharField(default='', max_length=255)),
                ('minSalary', models.IntegerField(default='')),
                ('maxSalary', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=255)),
                ('remark', models.CharField(default='', max_length=255)),
                ('assistant', models.CharField(default='', max_length=255)),
                ('overtime_pay', models.CharField(default='', max_length=255)),
                ('welfare', models.CharField(default='', max_length=255)),
                ('lineId', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='job_hunting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('job_type', models.CharField(default='', max_length=255)),
                ('minSalary', models.IntegerField(default='')),
                ('maxSalary', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=255)),
                ('remark', models.CharField(default='', max_length=255)),
                ('lineId', models.CharField(default='', max_length=255)),
                ('job_title', models.CharField(default='', max_length=255)),
                ('job_title2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
