# Generated by Django 4.0.5 on 2022-08-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('salary', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=255)),
                ('assistant', models.CharField(default='', max_length=255)),
                ('overtime_pay', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='job_hunting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('salary', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
