# Generated by Django 4.0.5 on 2022-08-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0003_remove_job_hunting_id_alter_job_hunting_lineid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_hunting',
            name='salary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
