# Generated by Django 4.0.5 on 2022-08-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0004_alter_job_hunting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_hunting',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
