# Generated by Django 3.2.8 on 2022-08-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0005_job_hunting_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_hunting',
            old_name='salary',
            new_name='maxSalary',
        ),
        migrations.AddField(
            model_name='job_hunting',
            name='minSalary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
