# Generated by Django 4.0.5 on 2022-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0006_auto_20220815_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
        migrations.AddField(
            model_name='company',
            name='companyName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='maxSalary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='minSalary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
