# Generated by Django 4.0.5 on 2022-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0007_remove_company_salary_company_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lineId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
