# Generated by Django 4.0.5 on 2022-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0009_job_hunting_job_title_job_hunting_job_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_hunting',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_hunting',
            name='lineId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
