# Generated by Django 4.0.5 on 2022-08-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0011_auto_20220823_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='maxSalary',
        ),
    ]
